StockRight/StockNews/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('news.html', views.news, name="news"),
]

StockRight/StockRight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('stockQuotes.urls')),
    path('',include('StockNews.urls')),
]

StockRight/stockQuotes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register.html', views.register, name='register'),
    path('login.html', views.login_view, name='login'),
    path('accounts/login/',views.login_view, name='login2'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.home, name='home'),
    path('myStocks.html', views.myStocks, name='myStocks'),
    path('delete/<stock_id>', views.deleteStock, name="deleteStock")
]

StockRight/stockQuotes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import DateTimeField
from datetime import datetime


class Stock(models.Model):
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    ticker = models.CharField(max_length=10)
    quantity = models.IntegerField(default=0)
    buyPrice = models.DecimalField(max_digits=19, decimal_places=10, default=0)
    added_at = models.DateTimeField(default=datetime.now())

    # def __str__(self):
    #     return self.ticker

StockRight/stockQuotes/forms.py
from django import forms
from .models import Stock
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class MyRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Provide a valid email address.')
    class Meta:
        model = User
        fields = ('first_name','last_name','username','email','password1','password2')

class StockForm(forms.ModelForm):
    def save(self,user=None, force_insert=False, force_update=False, commit=True):
        q = super(StockForm, self).save(commit=False)
        q.user = user
        if commit:
            q.save()
        return q
    class Meta:
        model = Stock
        exclude = ('user',)

StockRight/stockQuotes/views.py
from .models import Stock
from .forms import StockForm, MyRegistrationForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings

# IEX Publishable API Token: pk_8ffc6e63445e477fa4c225e7f9a30694 
# WTD Token (For Indices): lFxr8LrnAm6SsyOVrYZ7Z7Q4G4TOCAeGx6ikjFCCexwcbu8J6zuCOvUys69A
# Company name to ticker
# http://d.yimg.com/autoc.finance.yahoo.com/autoc?query=dollarama&region=1&lang=en&callback=YAHOO.Finance.SymbolSuggest.ssCallback

def register(request):
    if request.method == 'POST':
        form = MyRegistrationForm(request.POST or None)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            email = form.cleaned_data.get('email')
            user = authenticate(username=username, password=raw_password)

            subject = "Welcome to StockRight, "+str(username)+"!"
            message = "We hope our simplistic UI helps you manage your portfolio with zero clutter.\nThank you for your business.\n\nHappy Investing!\nStockRight Team"
            from_email = settings.EMAIL_HOST_USER
            to_list = [email]
            send_mail(subject,message,from_email,to_list)

            messages.success(request, f'Email Sent! New Account Created: {username}')
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, f'Please try again.')
    else:
        form = MyRegistrationForm()
    return render(request, 'register.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            print(user)
            login(request, user)
            messages.success(request, f'Welcome back {user.username}!')
            return redirect('home')
        else:
            messages.error(request, f'Please try again')
            return redirect('login')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form':form})

@login_required
def logout_view(request):
    logout(request)
    return redirect('home')

def obtainLogo(ticker):
    import requests
    import json

    url = "https://cloud.iexapis.com/stable/stock/"+ticker+"/logo?token=pk_8ffc6e63445e477fa4c225e7f9a30694"
    logo_req = requests.get(url)

    try:
        logo_url = json.loads(logo_req._content)
    except Exception as e:
        logo_url = "Invalid Ticker"

    return logo_url

def obtainCompanyData(ticker):
    import requests
    import json

    url = "https://cloud.iexapis.com/stable/stock/"+ticker+"/company?token=pk_8ffc6e63445e477fa4c225e7f9a30694"
    cInfo_req = requests.get(url)

    try:
        cInfo_url = json.loads(cInfo_req._content)
    except Exception as e:
        cInfo_url = "Company Info Unavailable"

    return cInfo_url

def getTickerFromName(company):
    import requests
    import json
    url1 = "http://d.yimg.com/autoc.finance.yahoo.com/autoc?query="+company+"&region=1&lang=en&callback=YAHOO.Finance.SymbolSuggest.ssCallback"
    company_req = requests.get(url1)

    try:
        company_data_string = company_req._content.decode()
        json_data_start_index = company_data_string.find('"Result":[{')+9
        company_data = json.loads(company_req._content.decode()[json_data_start_index:-4])
        cTicker = company_data[0]['symbol']
    except Exception as e:
        cTicker = "Invalid Company name."
    
    return cTicker

def stockSearch(ticker,company):
    import requests
    import json
    if company == "":
        url = "https://cloud.iexapis.com/stable/stock/"+ticker+"/quote?token=pk_8ffc6e63445e477fa4c225e7f9a30694"
        api_req = requests.get(url)

        try:
            api = json.loads(api_req._content)
            logo = obtainLogo(ticker)
            
            api['customLogo'] = logo['url']
            ytdChg = api['ytdChange']
            api['ytdChange'] = float(round(ytdChg*100,2))
            mktCap = api['marketCap']
            api['marketCap'] = str("{:,}".format(mktCap))
            avgVol = api["avgTotalVolume"]
            api["avgTotalVolume"] = str("{:,}".format(avgVol))

        except Exception as e:
            api = "Invalid Ticker"

        return api

    elif ticker == "":
        companyTicker = getTickerFromName(company)
        url2 = "https://cloud.iexapis.com/stable/stock/"+companyTicker+"/quote?token=pk_8ffc6e63445e477fa4c225e7f9a30694"
        api_req = requests.get(url2)
        try:
            api = json.loads(api_req._content)
            logo = obtainLogo(companyTicker)
            api['customLogo'] = logo['url']

            ytdChg = api['ytdChange']
            api['ytdChange'] = float(round(ytdChg*100,2))

            mktCap = api['marketCap']
            api['marketCap'] = str("{:,}".format(mktCap))

            avgVol = api["avgTotalVolume"]
            api["avgTotalVolume"] = str("{:,}".format(avgVol))

        except Exception as e:
            api = "Invalid Ticker"
            
        return api

def home(request):
    import requests
    import json

    if request.method == "POST":
        ticker = request.POST['ticker']
        company = request.POST['company']
        api = stockSearch(ticker,company)

        if ticker == "":
            cInfo = obtainCompanyData(getTickerFromName(company))
            if cInfo != "Company Info Unavailable":
                ceoName = cInfo['CEO']
                cInfo['customCEO'] = ceoName.replace(" ","_")
                no_of_employees = cInfo['employees']
                cInfo['employees'] = str("{:,}".format(no_of_employees))
            else:
                messages.error(request, f'{cInfo}')
        elif company == "":
            cInfo = obtainCompanyData(ticker)
            if cInfo != "Company Info Unavailable":
                ceoName = cInfo['CEO']
                cInfo['customCEO'] = ceoName.replace(" ","_")
                no_of_employees = cInfo['employees']
                cInfo['employees'] = str("{:,}".format(no_of_employees))
            else:
                messages.error(request, f'{cInfo}')
        
        if api == "Invalid Ticker":
            messages.error(request, f'{api}')
        elif api == "Invalid Company name.":
            messages.error(request, f'{api}')


        return render(request, 'home.html', {'api':api,'cInfo':cInfo})
    else:
        return render(request, 'home.html')

@login_required
def myStocks(request):
    import requests
    import json
    if request.method == 'POST':
        form = StockForm(request.POST or None)
        if form.is_valid():
            sForm = form.save(user = request.user)
            sForm.user = request.user
            sForm.save()
            messages.success(request, f'{str(sForm.ticker).upper()} has been added to your Portfolio.')
            return redirect('myStocks')
    else:
        form = StockForm()
        CurrUser = request.user
        tickers = Stock.objects.filter(user=CurrUser)
        stock_data = []
    
        for ticker in tickers:
            url = "https://cloud.iexapis.com/stable/stock/"+str(ticker.ticker)+"/quote?token=pk_8ffc6e63445e477fa4c225e7f9a30694"
            api_req = requests.get(url)

            try:
                api = json.loads(api_req._content)
                stock_data.append(api)

            except Exception as e:
                api = "Invalid Ticker"
            
            idx = stock_data.index(api)
            stock_data[idx]['customQuantity'] = ticker.quantity
            stock_data[idx]['customBuyPrice'] = float(round(ticker.buyPrice,2))
            stock_data[idx]['customTotalValue'] = ticker.quantity*stock_data[idx]['latestPrice']
            stock_data[idx]['customTotalReturn'] = float(round(((stock_data[idx]['customTotalValue'])-float(ticker.quantity*ticker.buyPrice)),2))
            difference = stock_data[idx]['customTotalValue'] - float(ticker.quantity*ticker.buyPrice)
            originalPrice = float(ticker.quantity*ticker.buyPrice)
            stock_data[idx]['customTotalReturnPercent'] = float(round((difference/originalPrice)*100,2))
            stock_data[idx]['customPurchaseDate'] = str(ticker.added_at)
            stock_data[idx]['customStock_id'] = ticker.id


        return render(request, 'myStocks.html', {'form':form,'ticker':tickers,'user':CurrUser, 'stock_data':stock_data})

@login_required
def deleteStock(request, stock_id):
    item = Stock.objects.get(pk=stock_id)
    item.delete()
    messages.success(request, f'{str(item.ticker).upper()} has been deleted from your Portfolio.')
    return redirect('myStocks')

StockRight/stockQuotes/templates/base.html
<!doctype html>
<html lang="en">

    <style>
        html {
            width: 100%; 
            height: 100%
        }
        body {
            width: 100%; 
            height: 100%
        }
        h6 {
            color: #0c2375;
        }
    </style>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">

        <link href='https://fonts.googleapis.com/css?family=Montserrat:400,600,700%7CSource+Sans+Pro:400,600,700' rel='stylesheet'>
        
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <script src="{% static 'js/lazysizes.min.js' %}"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>StockRight</title>
    </head>

    <body style="background-color:#0C0E15;">
        {% url 'home' as h_url %}
        {% url 'news' as n_url %}
        {% if request.get_full_path == h_url %}
            <!-- TradingView Widget BEGIN -->
            <div class="tradingview-widget-container" style="background-color: #0C0E15; ">
                <div class="tradingview-widget-container__widget" style="background-color: #0C0E15;"></div>
                <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>{
                    "symbols": 
                        [{"description": "S&P 500","proName": "TVC:SPX"},
                        {"description": "NASDAQ 100","proName": "NASDAQ:NDAQ"},
                        {"description": "USD/CAD","proName": "FX:USDCAD"},
                        {"description": "TSX Composite","proName": "TSX:TSX"},
                        {"description": "GOLD USD","proName": "TVC:GOLD"},
                        {"description": "CRUDE OIL","proName": "CURRENCYCOM:OIL_CRUDE"},
                        {"description": "SENSEX S&P","proName": "INDEX:SENSEX"
                        }],"colorTheme": "dark","isTransparent": false,"displayMode": "adaptive","locale": "en"}
                </script>
            </div>
            <!-- TradingView Widget END -->
        {% endif %}
        {% if request.get_full_path == n_url %}
            <!-- TradingView Widget BEGIN -->
            <div class="tradingview-widget-container" style="background-color: #0C0E15; ">
                <div class="tradingview-widget-container__widget" style="background-color: #0C0E15;"></div>
                <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js" async>{
                    "symbols": 
                        [{"description": "S&P 500","proName": "TVC:SPX"},
                        {"description": "NASDAQ 100","proName": "NASDAQ:NDAQ"},
                        {"description": "USD/CAD","proName": "FX:USDCAD"},
                        {"description": "TSX Composite","proName": "TSX:TSX"},
                        {"description": "GOLD USD","proName": "TVC:GOLD"},
                        {"description": "CRUDE OIL","proName": "CURRENCYCOM:OIL_CRUDE"},
                        {"description": "SENSEX S&P","proName": "INDEX:SENSEX"
                        }],"colorTheme": "dark","isTransparent": false,"displayMode": "adaptive","locale": "en"}
                </script>
            </div>
            <!-- TradingView Widget END -->
        {% endif %}

        <!-- Navigation Bar -->
        <nav class="navbar navbar-expand-lg navbar-dark" style=" background-color:#0c2375; z-index:1000;">
            <a href="{% url 'home' %}"><img class="img-responsive2" src="{% static 'img/logo1.png' %}" style="width: 80px;height: 80px;"></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="ture" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            &nbsp;&nbsp;
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myStocks' %}" style="color:#FFFFFF;">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'news' %}" style="color:#FFFFFF;">News</a>
                    </li>
                </ul>
                <ul class="navbar-nav mr-right">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#" style="color:#FFFFFF;">{{user.username}}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}" style="color:#FFFFFF;">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}" style="color:#FFFFFF;">Sign-In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}" style="color:#FFFFFF;">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <br/>
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-primary alert-dismissable" role="alert">
                        <button class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        {% block content %} {% endblock %}
        </div>

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/owl-carousel.min.js' %}"></script>
       <script src="{% static 'js/jquery.newsTicker.min.js' %}"></script>
        <script src="{% static 'js/modernizr.min.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>

        
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <style>
        footer.site-footer {
            background-color: #131722;
        }
        div.col-sm-12 > h6 {
            color: #0175F2;
        }
        div.col-sm-12 > p {
            color: white;
        }
        #credits {
            text-align: right;
        }
        #credits > h3 {
            color: #0175F2;
        }
        #credits > h4 {
            color:white;
        }
        #copyright {
            color:white;
        }
    </style>

    <!-- Site footer -->
    <footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <br/>
                <h6>About</h6>
                <p class="text-justify">
                    StockRight is a website that provides live prices, historical data, news articles, etc
                    It allows users to create an account which allows them to add stocks to thier watchlist and view additional information about the stock.
                </p>
            </div>
            <div id="credits" class="col-sm-12 col-md-6">
                <br/>
                <br/>
                <h3>Made By</h3>
                <h4>Akshar Gajjar & Rohan Patel</h4>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p id="copyright" class="copyright-text">Copyright &copy; 2020</p>
            </div>
        </div>
    </div>
    </footer>
    
</html>

StockRight/stockQuotes/templates/index.html
<html>
<head>
	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link href="{% static 'css/style1.css' %}" rel="stylesheet" type="text/css" media="all" />

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="{% static 'js/jquery.marquee.min.js' %}"></script>
</head>
<body>

<div class="banner-bottom">
	<script type="text/javascript">
		$(function () {
			$(".demo2").bootstrapNews({
				newsPerPage: 4,
				autoplay: true,
				pauseOnHover: true,
				navigation: false,
				direction: 'up',
				newsTickerInterval: 2500,
				onToDo: function () {
					//console.log(this);
				}
			});
		});
	</script>
	<script src="{% static 'js/jquery.bootstrap.newsbox.min.js' %}"></script>
	<div class='agileinfo_marquee' style="height: 40px; background-color: black;">
		<div data-speed="10" class="marquee" style="margin-top: 8px">
			<ul>
				{% for idx in api.data %}
				<li><a href= {{idx.news_url}} style="font-size: 15px; color: #ccc;">{{idx.title}}<span style="font-size: 15px"> | </span></a></li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>
<section class="slider">
	<div class="flexslider">
		<ul class="slides">
			<li>
				<div class="w3_agile_banner_text banner1">
					<h3>trade over world's leading stock exchanges with stockRight</h3>
					<div class="more">
						<a href="single.html" class="button button--isi button--text-thick button--text-upper button--size-s"><span>Learn More</span></a>
					</div>
				</div>
			</li>
			<li>
				<div class="w3_agile_banner_text banner5">
					<h4>grow your money with stockRight</h4>
				</div>
			</li>
		</ul>
	</div>
</section>

<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" property="" />
<script src="{% static 'js/jquery.flexslider.js' %}"></script>
<script type="text/javascript">
	$(window).load(function(){
		$('.flexslider').flexslider({
			animation: "slide",
			start: function(slider){
				$('body').removeClass('loading');
			}
		});
	});
</script>
	<div class="agileits_news_flash" style="margin-top: -420px">
		<h3><i class="fa fa-bolt" aria-hidden="true"></i>News Flash</h3>
		<div class="agileits_news_flash_table">
			<ul class="demo2" style="list-style: none;">
				{% for idx in api.data %}
				<li style="margin-left: 20px; " class="news-item1"><strong>{{idx.source_name}}: </strong>{{idx.title}}</li>
				{% endfor %}
			</ul>
			<br>
		</div>
	</div>

	<div class="agileits_news_flash">
		<h3><i class="fa fa-bolt" aria-hidden="true"></i>Top Mentioned Stocks</h3>
		<div class="agileits_news_flash_table">
			<ul class="demo2" style="list-style: none;">
				{% for idx in api1.data.all %}
				<li style="margin-left: 20px; " class="news-item1"><strong>{{idx.ticker}}: </strong>{{idx.name}} | Sentiment Score: {{idx.sentiment_score}} |</li>
				{% endfor %}
			</ul>
			<br>
		</div>
	</div>

<script>
	$('.marquee').marquee({
		gap: 150,
		delayBeforeStart: 0,
		direction: 'left',
		duplicated: true,
		pauseOnHover: true,
		duration: 15000
	});
</script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

StockRight/stockQuotes/templates/myStocks.html
{% extends 'base.html' %} {% block content %}
{% load widget_tweaks %}


<style>
    #portfolioCont {
        align-content: center;
        align-items: center;
        padding-left: 10px;
        padding-right: 10px;
        width: 100%;
    }
    h1 {
        margin: 0;
        display: inline-block;
        color: white;
    }
    label {
        color: white;
    }
    h4 {
        color: white;
    }
    p {
        color: white;
    }
    a {
        color: white;
        text-decoration: wavy;
    }
    div.modal-content {
        border-color: #1C202B;
        border: #1C202B;
    }
    div.modal-header {
        background-color:#0c2375;
    }
    div.modal-body {
        background-color:#1C202B;
    }
    div.modal-footer {
        background-color:#1C202B;
    }
    #closeBtn {
        color: white;
    }
    button.btn {
        float: right;
        background-color:#0c2375; 
        color: white;
    }
    h5.modal-title {
        color: white;
    }
    input.form-control:focus, textarea {
        background-color:#131722; 
        color:white;
        outline-color: #0c2375;
    }
    input.form-control {
        background-color:#131722; 
        color:white;
        outline-color: #0c2375;
    }
    #id_added_at {
        background-color:#1d2231;
        color: #9e9e9e;
        pointer-events:none;
    }
</style>

<div class="container" id="portfolioCont">
    <h1>{{user}}'s Portfolio</h1>
    <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#addStockModal">Add Stock</button>
    <div class="modal fade" id="addStockModal" tabindex="-1" role="dialog" aria-labelledby="addStockModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="addStockModalLabel">Add Stock</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span id="closeBtn" aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <form method="post" novalidate>
                        {% csrf_token %}

                        {% for hidden_field in form.hidden_fields %}
                            {{ hidden_field }}
                        {% endfor %}

                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                            </div>
                        {% endif %}

                        {% for field in form.visible_fields %}
                            <div class="form-group">
                                {{ field.label_tag }}

                                {% if form.is_bound %}
                                    {% if field.errors %}
                                    {% render_field field class="form-control is-invalid" %}
                                    {% for error in field.errors %}
                                        <div class="invalid-feedback">
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                    {% else %}
                                    {% render_field field class="form-control is-valid" %}
                                    {% endif %}
                                {% else %}
                                    {% render_field field class="form-control" %}
                                {% endif %}
                            </div>
                        {% endfor %}
                        <br/>
                        <button class="btn btn-block" type="submit" name="action">Submit</button>
                    </form>
                    <script type="text/javascript">
                        function forceKeyPressUppercase(e)
                        {
                            var charInput = e.keyCode;
                            if((charInput >= 97) && (charInput <= 122)) { // lowercase
                                if(!e.ctrlKey && !e.metaKey && !e.altKey) { // no modifier key
                                    var newChar = charInput - 32;
                                    var start = e.target.selectionStart;
                                    var end = e.target.selectionEnd;
                                    e.target.value = e.target.value.substring(0, start) + String.fromCharCode(newChar) + e.target.value.substring(end);
                                    e.target.setSelectionRange(start+1, start+1);
                                    e.preventDefault();
                                }
                            }
                        }
                        document.getElementById("id_ticker").addEventListener("keypress", forceKeyPressUppercase, false);
                    </script>
                </div>
            </div>
        </div>
    </div>

    <br/>
    <br/>


    <style>
        table.table {
            background-color:#1B1F2A;
            color:white;
        }
        table.table > tbody > tr:hover {
            background-color: #0C2375;
            color:white;
        }
        table.table > thead {
            background-color: #0C2375;
            color:white;
        }
    </style>

    <div class="table-responsive-xl">
        <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col">Company Name/Ticker</th>
                <th scope="col">Shares</th>
                <th scope="col">Total Value</th>

                <th scope="col">Buy Price</th>
                <th scope="col">Latest Price</th>
                <th scope="col">Total Return(%)</th>

                <th scope="col">Prev. Close</th>
                <th scope="col">Change(%)</th>

                <th scope="col">Date Added</th>
                <th scope="col">Management</th>
                </tr>
            </thead>
            <tbody>
                {% if ticker %}
                    {% for stock in stock_data %}
                        <tr>
                            <th scope="row">{{stock.companyName}} | {{stock.symbol}}</th>
                            <td>{{stock.customQuantity}}</td>
                            <td>${{stock.customTotalValue}}</td>

                            <td>${{stock.customBuyPrice}}</td>
                            <td>${{stock.latestPrice}}</td>
                            <td>${{stock.customTotalReturn}} ({{stock.customTotalReturnPercent}}%)</td>

                            <td>${{stock.previousClose}}</td>
                            <td>${{stock.change}} ({{stock.changePercent}}%)</td>

                            <td>{{stock.customPurchaseDate}}</td>
                            <td><a href="{% url 'deleteStock' stock.customStock_id %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}